name: tests
on:
  push:
    branches: [ '*' ]
  pull_request:
   branches: [ '*' ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: npm install and npm run CI commands
      run: |
        npm i
        npm run test
  call-build:
    needs: test
    uses: ./.github/workflows/build.yml
    secrets: inherit